# TL;DR: YOU SHOULD DELETE THIS FILE
#
# This file was generated by Cucumber-Rails and is only here to get you a head start
# These step definitions are thin wrappers around the Capybara/Webrat API that lets you
# visit pages, interact with widgets and make assertions about page content.
#
# If you use these step definitions as basis for your features you will quickly end up
# with features that are:
#
# * Hard to maintain
# * Verbose to read
#
# A much better approach is to write your own higher level step definitions, following
# the advice in the following blog posts:
#
# * http://benmabey.com/2008/05/19/imperative-vs-declarative-scenarios-in-user-stories.html
# * http://dannorth.net/2011/01/31/whose-domain-is-it-anyway/
# * http://elabs.se/blog/15-you-re-cuking-it-wrong
#
# frozen_string_literal: true
require 'uri'
require 'cgi'
require File.expand_path(File.join(__dir__, '..', 'support', 'paths'))
require File.expand_path(File.join(__dir__, '..', 'support', 'selectors'))

module WithinHelpers
  def with_scope(locator)
    locator ? within(*selector_for(locator)) { yield } : yield
  end
end
World(WithinHelpers)

When(/^(.*) within (.*[^:])$/)      { |s, parent| with_scope(parent) { step s } }
When(/^(.*) within (.*[^:]):$/)     { |s, parent, blob| with_scope(parent) { step "#{s}:", blob } }

Given(/^(?:|I )am on (.+)$/)                   { |p| visit path_to(p) }
When(/^(?:|I )go to (.+)$/)                    { |p| visit path_to(p) }
When(/^(?:|I )press "([^"]*)"$/)               { |b| click_button(b) }
When(/^(?:|I )follow "([^"]*)"$/)              { |l| click_link(l) }
When(/^(?:|I )fill in "([^"]*)" with "([^"]*)"$/) { |f, v| fill_in(f, with: v) }
When(/^(?:|I )fill in "([^"]*)" for "([^"]*)"$/)  { |v, f| fill_in(f, with: v) }

When(/^(?:|I )fill in the following:$/) do |table|
  table.rows_hash.each { |name, value| step %(I fill in "#{name}" with "#{value}") }
end

When(/^(?:|I )select "([^"]*)" from "([^"]*)"$/) { |v, f| select(v, from: f) }
When(/^(?:|I )check (?:the\s+)?"([^"]*)"(?:\s*checkbox)?$/)   { |f| check(f) }
When(/^(?:|I )uncheck (?:the\s+)?"([^"]*)"(?:\s*checkbox)?$/) { |f| uncheck(f) }
When(/^(?:|I )choose "([^"]*)"$/)                            { |f| choose(f) }
When(/^(?:|I )attach the file "([^"]*)" to "([^"]*)"$/)      { |p, f| attach_file(f, File.expand_path(p)) }

Then('I expect to see {string}')                       { |s| expect(page).to have_content(s) }
Then(/^(?:|I )should see "([^"]*)"$/)                  { |t| expect(page).to have_content(t) }
Then(/^(?:|I )should not see "([^"]*)"$/)              { |t| expect(page).not_to have_content(t) }

Then(/^(?:|I )should see \/([^\/]*)\/$/) do |pat|
  expect(page).to have_xpath('//*', text: Regexp.new(pat))
end

Then(/^(?:|I )should not see \/([^\/]*)\/$/) do |pat|
  expect(page).to have_no_xpath('//*', text: Regexp.new(pat))
end

Then(/^the "([^"]*)" field(?: within (.*))? should contain "([^"]*)"$/) do |fld, parent, val|
  with_scope(parent) do
    el = find_field(fld)
    txt = el.tag_name == 'textarea' ? el.text : el.value
    expect(txt).to match(/#{val}/)
  end
end

Then(/^the "([^"]*)" field(?: within (.*))? should not contain "([^"]*)"$/) do |fld, parent, val|
  with_scope(parent) do
    el = find_field(fld)
    txt = el.tag_name == 'textarea' ? el.text : el.value
    expect(txt).not_to match(/#{val}/)
  end
end

Then(/^the "([^"]*)" field should have the error "([^"]*)"$/) do |fld, msg|
  el            = find_field(fld)
  parent_classes = el.find(:xpath, '..')[:class].split(' ')

  form            = el.find(:xpath, 'ancestor::form[1]')
  formtastic      = form[:class].include?('formtastic')
  error_classname = formtastic ? 'error' : 'field_with_errors'

  expect(parent_classes).to include(error_classname)

  if formtastic
    inline_err = el.find(:xpath, '../*[@class="inline-errors"][1]')
    expect(inline_err).to have_content(msg)
  else
    expect(page).to have_content("#{fld.titleize} #{msg}")
  end
end

Then(/^the "([^"]*)" field should have no error$/) do |fld|
  el     = find_field(fld)
  parent = el.find(:xpath, '..')[:class].split(' ')
  expect(parent).not_to include('field_with_errors')
  expect(parent).not_to include('error')
end

Then(/^the "([^"]*)" checkbox(?: within (.*))? should be checked$/) do |lbl, parent|
  with_scope(parent) { expect(find_field(lbl)['checked']).to be_truthy }
end

Then(/^the "([^"]*)" checkbox(?: within (.*))? should not be checked$/) do |lbl, parent|
  with_scope(parent) { expect(find_field(lbl)['checked']).to be_falsey }
end

Then(/^(?:|I )should be on (.+)$/) do |page_name|
  expect(URI.parse(current_url).path).to eq(path_to(page_name))
end

Then(/^(?:|I )should have the following query string:$/) do |pairs|
  query          = URI.parse(current_url).query
  actual_params  = query ? CGI.parse(query) : {}
  expected_params = pairs.rows_hash.transform_values { |v| v.split(',') }

  expect(actual_params).to eq(expected_params)
end

Then(/^show me the page$/) { save_and_open_page }
